language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g purescript@^0.12 pulp bower purescript-psa
  - bower install
script:
  - pulp test
  - npm run example-styled-components-box
  - npm run example-styled-components-buttons
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
